# Generated by Django 2.2.7 on 2019-11-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
